//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.PluginDeployer.Entities
{
    /// <summary>
    /// A component dependency in CRM.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dependency")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xrm.PluginDeployer.DevTool.BackEndEarlyBind", "1.0")]
    public partial class Dependency : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public Dependency() : 
                base(EntityLogicalName)
        {
        }

        /// <summary/>
        public const string EntityLogicalName = "dependency";
        
        /// <summary/>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary/>
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        
        /// <summary/>
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary/>
        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }


        /// <summary>
        /// Unique identifier of a dependency.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencyid")]
        public System.Nullable<System.Guid> DependencyId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("dependencyid");
            }
            set
            {
                this.OnPropertyChanging("DependencyId");
                this.SetAttributeValue("dependencyid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("DependencyId");
            }
        }

        /// <summary/>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencyid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.DependencyId = value;
            }
        }

        /// <summary>
        /// The dependency type of the dependency.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencytype")]
        public Microsoft.Xrm.Sdk.OptionSetValue DependencyType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("dependencytype");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentbasesolutionid")]
        public System.Nullable<System.Guid> DependentComponentBaseSolutionId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("dependentcomponentbasesolutionid");
            }
        }

        /// <summary>
        /// Unique identifier of the dependent component's node.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentnodeid")]
        public Microsoft.Xrm.Sdk.EntityReference DependentComponentNodeId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dependentcomponentnodeid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentobjectid")]
        public System.Nullable<System.Guid> DependentComponentObjectId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("dependentcomponentobjectid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponentparentid")]
        public System.Nullable<System.Guid> DependentComponentParentId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("dependentcomponentparentid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependentcomponenttype")]
        public Microsoft.Xrm.Sdk.OptionSetValue DependentComponentType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("dependentcomponenttype");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentbasesolutionid")]
        public System.Nullable<System.Guid> RequiredComponentBaseSolutionId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("requiredcomponentbasesolutionid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentintroducedversion")]
        public System.Nullable<double> RequiredComponentIntroducedVersion
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("requiredcomponentintroducedversion");
            }
        }

        /// <summary>
        /// Unique identifier of the required component's node
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentnodeid")]
        public Microsoft.Xrm.Sdk.EntityReference RequiredComponentNodeId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("requiredcomponentnodeid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentobjectid")]
        public System.Nullable<System.Guid> RequiredComponentObjectId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("requiredcomponentobjectid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponentparentid")]
        public System.Nullable<System.Guid> RequiredComponentParentId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("requiredcomponentparentid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requiredcomponenttype")]
        public Microsoft.Xrm.Sdk.OptionSetValue RequiredComponentType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("requiredcomponenttype");
            }
        }

        /// <summary/>
        public class OptionSet
        {

            /// <summary/>
            public enum ComponentType
            {

                /// <summary/>
                Entity = 1,

                /// <summary/>
                Attribute = 2,

                /// <summary/>
                Relationship = 3,

                /// <summary/>
                AttributePicklistValue = 4,

                /// <summary/>
                AttributeLookupValue = 5,

                /// <summary/>
                ViewAttribute = 6,

                /// <summary/>
                LocalizedLabel = 7,

                /// <summary/>
                RelationshipExtraCondition = 8,

                /// <summary/>
                OptionSet = 9,

                /// <summary/>
                EntityRelationship = 10,

                /// <summary/>
                EntityRelationshipRole = 11,

                /// <summary/>
                EntityRelationshipRelationships = 12,

                /// <summary/>
                ManagedProperty = 13,

                /// <summary/>
                EntityKey = 14,

                /// <summary/>
                Role = 20,

                /// <summary/>
                RolePrivilege = 21,

                /// <summary/>
                DisplayString = 22,

                /// <summary/>
                DisplayStringMap = 23,

                /// <summary/>
                Form = 24,

                /// <summary/>
                Organization = 25,

                /// <summary/>
                SavedQuery = 26,

                /// <summary/>
                Workflow = 29,

                /// <summary/>
                Report = 31,

                /// <summary/>
                ReportEntity = 32,

                /// <summary/>
                ReportCategory = 33,

                /// <summary/>
                ReportVisibility = 34,

                /// <summary/>
                Attachment = 35,

                /// <summary/>
                EmailTemplate = 36,

                /// <summary/>
                ContractTemplate = 37,

                /// <summary/>
                KbArticleTemplate = 38,

                /// <summary/>
                MailMergeTemplate = 39,

                /// <summary/>
                DuplicateRule = 44,

                /// <summary/>
                DuplicateRuleCondition = 45,

                /// <summary/>
                EntityMap = 46,

                /// <summary/>
                AttributeMap = 47,

                /// <summary/>
                RibbonCommand = 48,

                /// <summary/>
                RibbonContextGroup = 49,

                /// <summary/>
                RibbonCustomization = 50,

                /// <summary/>
                RibbonRule = 52,

                /// <summary/>
                RibbonTabToCommandMap = 53,

                /// <summary/>
                RibbonDiff = 55,

                /// <summary/>
                SavedQueryVisualization = 59,

                /// <summary/>
                SystemForm = 60,

                /// <summary/>
                WebResource = 61,

                /// <summary/>
                SiteMap = 62,

                /// <summary/>
                ConnectionRole = 63,

                /// <summary/>
                FieldSecurityProfile = 70,

                /// <summary/>
                FieldPermission = 71,

                /// <summary/>
                PluginType = 90,

                /// <summary/>
                PluginAssembly = 91,

                /// <summary/>
                SdkMessageProcessingStep = 92,

                /// <summary/>
                SdkMessageProcessingStepImage = 93,

                /// <summary/>
                ServiceEndpoint = 95,

                /// <summary/>
                RoutingRule = 150,

                /// <summary/>
                RoutingRuleItem = 151,

                /// <summary/>
                Sla = 152,

                /// <summary/>
                SlaItem = 153,

                /// <summary/>
                ConvertRule = 154,

                /// <summary/>
                ConvertRuleItem = 155,

                /// <summary/>
                HierarchyRule = 65,

                /// <summary/>
                MobileOfflineProfile = 161,

                /// <summary/>
                MobileOfflineProfileItem = 162,

                /// <summary/>
                SimilarityRule = 165,

                /// <summary/>
                CustomControl = 66,

                /// <summary/>
                CustomControlDefaultConfig = 68,
            }

            /// <summary/>
            public enum DependencyType
            {

                /// <summary/>
                None = 0,

                /// <summary/>
                SolutionInternal = 1,

                /// <summary/>
                Published = 2,

                /// <summary/>
                Unpublished = 4,
            }

        }

        /// <summary/>
        public class PropertyNames
        {

            /// <summary/>
            public const string DependencyId = "dependencyid";

            /// <summary/>
            public const string DependencyType = "dependencytype";

            /// <summary/>
            public const string DependencyTypeName = "dependencytypename";

            /// <summary/>
            public const string DependentComponentBaseSolutionId = "dependentcomponentbasesolutionid";

            /// <summary/>
            public const string DependentComponentNodeId = "dependentcomponentnodeid";

            /// <summary/>
            public const string DependentComponentNodeIdName = "dependentcomponentnodeidname";

            /// <summary/>
            public const string DependentComponentObjectId = "dependentcomponentobjectid";

            /// <summary/>
            public const string DependentComponentParentId = "dependentcomponentparentid";

            /// <summary/>
            public const string DependentComponentType = "dependentcomponenttype";

            /// <summary/>
            public const string DependentComponentTypeName = "dependentcomponenttypename";

            /// <summary/>
            public const string RequiredComponentBaseSolutionId = "requiredcomponentbasesolutionid";

            /// <summary/>
            public const string RequiredComponentIntroducedVersion = "requiredcomponentintroducedversion";

            /// <summary/>
            public const string RequiredComponentNodeId = "requiredcomponentnodeid";

            /// <summary/>
            public const string RequiredComponentNodeIdName = "requiredcomponentnodeidname";

            /// <summary/>
            public const string RequiredComponentObjectId = "requiredcomponentobjectid";

            /// <summary/>
            public const string RequiredComponentParentId = "requiredcomponentparentid";

            /// <summary/>
            public const string RequiredComponentType = "requiredcomponenttype";

            /// <summary/>
            public const string RequiredComponentTypeName = "requiredcomponenttypename";

        }

        /// <summary/>
        public class Ref
        {
        }
    }

    /// <summary>
    /// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    public partial class CrmContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
    {

        /// <summary>
        /// Gets a binding to the set of all <see cref="Xrm.PluginDeployer.Entities.Dependency"/> entities.
        /// </summary>
        public System.Linq.IQueryable<Xrm.PluginDeployer.Entities.Dependency> DependencySet
        {
            get
            {
                return this.CreateQuery<Xrm.PluginDeployer.Entities.Dependency>();
            }
        }
    }
}
